disabled_rules: # rule identifiers to exclude from running
  - todo
  - closure_parameter_position
  - trailing_whitespace # this is default Xcode behavior
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
