disabled_rules: # rule identifiers to exclude from running
  - todo
  - closure_parameter_position
opt_in_rules:
  - force_unwrapping
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
