# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'Steps4Impact.xcworkspace'
    scheme: 'Steps4Impact'

- task: Xcode@5
  inputs:
    actions: 'test'
    configuration: 'Release'
    sdk: 'iphonesimulator'
    xcWorkspacePath: 'Steps4Impact.xcworkspace'
    scheme: 'Steps4Impact'
    destinationPlatformOption: iOS
    destinationTypeOption: simulators
    destinationSimulators: 'iPhone SE'
    args: 'test'
    publishJUnitResults: true