# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - '*'

pool:
  vmImage: 'macOS-10.14'

steps:
- task: DownloadSecureFile@1
  name: GooglePlist
  displayName: 'Download Firebase Credentials'
  inputs:
    secureFile: 'GoogleService-Info.plist'

- script: |
    echo $(GooglePlist.secureFilePath)
    cp $(GooglePlist.secureFilePath) '$(Pipeline.Workspace)/s/Steps4Impact/Supporting Files/'

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'Steps4Impact.xcworkspace'
    scheme: 'Steps4Impact'

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Debug'
    sdk: 'iphonesimulator'
    xcWorkspacePath: 'Steps4Impact.xcworkspace'
    scheme: 'Steps4Impact'
    destinationPlatformOption: iOS
    destinationTypeOption: simulators
    destinationSimulators: 'iPhone 8'
    args: 'test'
    publishJUnitResults: true